cmake_minimum_required(VERSION 3.10)
project(lib_c CXX)
set(CMAKE_CXX_STANDARD 17)
file(GLOB SOURCES "*.cpp")
add_library(lib_c STATIC ${SOURCES})
target_include_directories(lib_c PUBLIC ${CMAKE_INSTALL_PREFIX}/include)
find_library(CORE_LIB core PATHS ${CMAKE_INSTALL_PREFIX}/lib REQUIRED)
target_link_libraries(lib_c PUBLIC ${CORE_LIB})
install(TARGETS lib_c ARCHIVE DESTINATION lib)
install(FILES lib_c.hpp DESTINATION include)
