#!/usr/bin/env python3
"""Generate the real C++ sources for examples/06-macro-micro-optimization.

Same convention as examples/05-cmake-cpp-toolchain/generate_sources.py:
sources are generated once and committed, so nothing but a real C++
toolchain is needed inside the sandbox at build time.

Unlike 05's, every translation unit here is *deliberately calibrated* to
cost roughly one second of real `g++` time (a constexpr table built from
a recursive template accumulator - `WEIGHT` below is close to linear in
compile time; 600 measured ~1.1s on the host this was calibrated on).
That matters because this project exists to make a real, measurable
macro-vs-micro optimization difference visible to `bga`: with
sub-100ms translation units the whole signal drowns in BuildStream's own
per-element sandbox-staging overhead.

Run from the repository root:

    python3 examples/06-macro-micro-optimization/generate_sources.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
# Both the baseline project and its `optimized/` sibling get a real,
# byte-identical copy of every source file. BuildStream rejects a `local`
# source whose path leads outside its own project directory ("Specified
# path 'files/src/app' must not lead outside of the project directory"),
# so the two variants cannot share one directory via a symlink - the copy
# is the only way to keep them provably identical, and generating both
# from this one script is what keeps them that way.
SRC_ROOTS = (
    os.path.join(HERE, "files", "src"),
    os.path.join(HERE, "optimized", "files", "src"),
)

# Compile-cost knob - see module docstring. Close to linear in real g++
# wall-clock; keep it modest so a full baseline build stays under a
# minute on a 4-core machine.
WEIGHT = 600

TU_TEMPLATE = """\
// Generated by examples/06-macro-micro-optimization/generate_sources.py -
// do not edit by hand. Deliberately expensive to compile (see that
// script's docstring): a real ~1s translation unit, so this project's
// element durations are dominated by real compilation rather than by
// BuildStream's own sandbox-staging overhead.
#include <array>
#include <cstddef>
#include <utility>

#include "{header}"

namespace {{

template <std::size_t N, std::size_t S>
struct Acc {{
    static constexpr std::size_t value =
        (Acc<N - 1, S>::value * 1664525u + 1013904223u + S) % 4294967291u;
}};

template <std::size_t S>
struct Acc<0, S> {{
    static constexpr std::size_t value = S;
}};

template <std::size_t... I>
constexpr auto make_table(std::index_sequence<I...>) {{
    return std::array<std::size_t, sizeof...(I)>{{Acc<60, I + {salt}>::value...}};
}}

constexpr auto table = make_table(std::make_index_sequence<{weight}>{{}});

}}  // namespace

std::size_t {symbol}(std::size_t i) {{
    return table[i % table.size()];
}}
"""

HEADER_TEMPLATE = """\
// Generated by examples/06-macro-micro-optimization/generate_sources.py.
#pragma once
#include <cstddef>

{decls}
"""

CMAKE_TEMPLATE = """\
# Generated by examples/06-macro-micro-optimization/generate_sources.py.
cmake_minimum_required(VERSION 3.10)
project({name} CXX)
set(CMAKE_CXX_STANDARD 17)
file(GLOB SOURCES "*.cpp")
add_library({name} STATIC ${{SOURCES}})
target_include_directories({name} PUBLIC $<INSTALL_INTERFACE:include>)
install(TARGETS {name} ARCHIVE DESTINATION lib)
install(FILES {name}.hpp DESTINATION include)
"""

APP_CMAKE = """\
# Generated by examples/06-macro-micro-optimization/generate_sources.py.
cmake_minimum_required(VERSION 3.10)
project(app CXX)
set(CMAKE_CXX_STANDARD 17)
file(GLOB SOURCES "*.cpp")
add_executable(app ${SOURCES})
install(TARGETS app RUNTIME DESTINATION bin)
"""

# name -> number of ~1s translation units. Sized so the *baseline*
# (deliberately mis-optimized) topology has a clearly visible critical
# path: a heavy `core` that is forced serial by `notparallel`, then six
# libraries chained one after another when they could all fan out.
MODULES = {
    "core": 8,
    "codegen": 4,
    "lib-a": 3,
    "lib-b": 3,
    "lib-c": 3,
    "lib-d": 3,
    "lib-e": 3,
    "lib-f": 3,
}

APP_TUS = 2


def write(relpath: str, text: str) -> None:
    """Write one generated file into every source root (see SRC_ROOTS)."""
    for root in SRC_ROOTS:
        path = os.path.join(root, relpath)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)


def symbolize(name: str) -> str:
    return name.replace("-", "_")


def main() -> None:
    salt = 0
    for name, tu_count in MODULES.items():
        sym = symbolize(name)
        module_dir = name
        decls = []
        for i in range(tu_count):
            salt += 1
            symbol = "{}_probe_{}".format(sym, i)
            decls.append("std::size_t {}(std::size_t i);".format(symbol))
            write(
                os.path.join(module_dir, "unit_{}.cpp".format(i)),
                TU_TEMPLATE.format(
                    header="{}.hpp".format(name),
                    salt=salt * 977,
                    weight=WEIGHT,
                    symbol=symbol,
                ),
            )
        write(
            os.path.join(module_dir, "{}.hpp".format(name)),
            HEADER_TEMPLATE.format(decls="\n".join(decls)),
        )
        write(
            os.path.join(module_dir, "CMakeLists.txt"),
            CMAKE_TEMPLATE.format(name=name),
        )

    app_dir = "app"
    for i in range(APP_TUS):
        salt += 1
        write(
            os.path.join(app_dir, "unit_{}.cpp".format(i)),
            TU_TEMPLATE.format(
                header="app.hpp", salt=salt * 977, weight=WEIGHT,
                symbol="app_probe_{}".format(i),
            ),
        )
    write(
        os.path.join(app_dir, "app.hpp"),
        HEADER_TEMPLATE.format(
            decls="\n".join(
                "std::size_t app_probe_{}(std::size_t i);".format(i)
                for i in range(APP_TUS)
            )
        ),
    )
    write(
        os.path.join(app_dir, "main.cpp"),
        '#include <cstdio>\n#include "app.hpp"\n\n'
        "int main() {\n"
        "    std::size_t acc = 0;\n"
        + "".join(
            "    acc += app_probe_{}(acc + {});\n".format(i, i) for i in range(APP_TUS)
        )
        + '    std::printf("%zu\\n", acc);\n'
        "    return 0;\n"
        "}\n",
    )
    write(os.path.join(app_dir, "CMakeLists.txt"), APP_CMAKE)
    for root in SRC_ROOTS:
        print("Generated sources under {}".format(root))


if __name__ == "__main__":
    main()
