cmake_minimum_required(VERSION 3.10)
project(lib_b CXX)
set(CMAKE_CXX_STANDARD 17)
file(GLOB SOURCES "*.cpp")
add_library(lib_b STATIC ${SOURCES})
target_include_directories(lib_b PUBLIC ${CMAKE_INSTALL_PREFIX}/include)
find_library(CORE_LIB core PATHS ${CMAKE_INSTALL_PREFIX}/lib REQUIRED)
target_link_libraries(lib_b PUBLIC ${CORE_LIB})
install(TARGETS lib_b ARCHIVE DESTINATION lib)
install(FILES lib_b.hpp DESTINATION include)
