cmake_minimum_required(VERSION 3.10)
project(app CXX)
set(CMAKE_CXX_STANDARD 17)
add_executable(app main.cpp)
target_include_directories(app PRIVATE ${CMAKE_INSTALL_PREFIX}/include)
foreach(dep core lib_a lib_b lib_c lib_d)
  find_library(LIB_${dep} ${dep} PATHS ${CMAKE_INSTALL_PREFIX}/lib REQUIRED)
  target_link_libraries(app PRIVATE ${LIB_${dep}})
endforeach()
install(TARGETS app RUNTIME DESTINATION bin)
