// Generated by examples/06-macro-micro-optimization/generate_sources.py.
#pragma once
#include <cstddef>

std::size_t lib_f_probe_0(std::size_t i);
std::size_t lib_f_probe_1(std::size_t i);
std::size_t lib_f_probe_2(std::size_t i);
