// Generated by examples/06-macro-micro-optimization/generate_sources.py.
#pragma once
#include <cstddef>

std::size_t core_probe_0(std::size_t i);
std::size_t core_probe_1(std::size_t i);
std::size_t core_probe_2(std::size_t i);
std::size_t core_probe_3(std::size_t i);
std::size_t core_probe_4(std::size_t i);
std::size_t core_probe_5(std::size_t i);
std::size_t core_probe_6(std::size_t i);
std::size_t core_probe_7(std::size_t i);
