// Generated by examples/06-macro-micro-optimization/generate_sources.py -
// do not edit by hand. Deliberately expensive to compile (see that
// script's docstring): a real ~1s translation unit, so this project's
// element durations are dominated by real compilation rather than by
// BuildStream's own sandbox-staging overhead.
#include <array>
#include <cstddef>
#include <utility>

#include "app.hpp"

namespace {

template <std::size_t N, std::size_t S>
struct Acc {
    static constexpr std::size_t value =
        (Acc<N - 1, S>::value * 1664525u + 1013904223u + S) % 4294967291u;
};

template <std::size_t S>
struct Acc<0, S> {
    static constexpr std::size_t value = S;
};

template <std::size_t... I>
constexpr auto make_table(std::index_sequence<I...>) {
    return std::array<std::size_t, sizeof...(I)>{Acc<60, I + 31264>::value...};
}

constexpr auto table = make_table(std::make_index_sequence<600>{});

}  // namespace

std::size_t app_probe_1(std::size_t i) {
    return table[i % table.size()];
}
