cmake_minimum_required(VERSION 3.10)
project(tiny-merged CXX)
set(CMAKE_CXX_STANDARD 17)
add_library(tiny-1 STATIC tiny-1.cpp)
add_library(tiny-2 STATIC tiny-2.cpp)
add_library(tiny-3 STATIC tiny-3.cpp)
add_library(tiny-4 STATIC tiny-4.cpp)
add_library(tiny-5 STATIC tiny-5.cpp)
add_library(tiny-6 STATIC tiny-6.cpp)
add_library(tiny-7 STATIC tiny-7.cpp)
add_library(tiny-8 STATIC tiny-8.cpp)
install(TARGETS tiny-1 tiny-2 tiny-3 tiny-4 tiny-5 tiny-6 tiny-7 tiny-8 ARCHIVE DESTINATION lib)
